sudo: false
language: node_js
node_js:
  - "node"
script:
  - 'yarn lint'
  - 'yarn unused'
cache:
  yarn: true
  directories:
    - packages/eslint-config-sensu/node_modules
    - packages/eslint-config-sensu-react/node_modules
