---
dist: trusty
language: node_js
node_js:
  - 9
cache:
  directories:
    - node_modules
    - packages/eslint-config-sensu/node_modules
    - packages/eslint-config-sensu-react/node_modules
    - packages/eslint-config-sensu-flow/node_modules
install: true
script:
  - 'git clean -fdX .'
  - 'yarn'
  - 'yarn lint'
  - 'yarn unused'
